name: Exodus
version: 1.1.1
description: The RPG plugin for Exodus
author: MastaC
website: http://www.tidesofwaronline.com
main: com.tidesofwaronline.Exodus.Exodus
softdepend: [RemoteEntities, TagAPI]
depend: [ProtocolLib, WorldEdit, Vault]

commands:
  stats:
    description: Displays the stats menu.
  exo:
    description: Exodus Admin command.
    aliases: [xo]
  exospawner:
    description: Controls Exodus Spawners
    aliases: [es]
  party:
    description: Exodus Party commands.
  guild:
    description: Exodus Guild commands.
  dbe:
    description: Dungeon Block Editor system command.
  gift:
    description: Give and receive gifts!